# Generated by Django 5.2.7 on 2025-10-20 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Полное имя сотрудника (Фамилия Имя Отчество)",
                        max_length=255,
                        verbose_name="ФИО",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        help_text="Должность сотрудника в компании",
                        max_length=255,
                        verbose_name="Должность",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Корпоративная почта сотрудника",
                        max_length=254,
                        unique=True,
                        verbose_name="Электронная почта",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text='Название отдела (например, "Разработка", "Маркетинг")',
                        max_length=100,
                        verbose_name="Отдел",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите галочку, если сотрудник уволен или в длительном отпуске",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(
                        blank=True,
                        help_text="Укажите дату трудоустройства",
                        null=True,
                        verbose_name="Дата приёма на работу",
                    ),
                ),
                (
                    "workload_capacity",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="Максимальное количество активных задач, которые может выполнять сотрудник",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Макс. нагрузка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
                "ordering": ["full_name"],
            },
        ),
    ]
